### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by khodya** [vmlysenkov/GridU-final-task#20]
1. Remove code with `Calendar` and unused methods
2. Remove ignored tests with `Calendar` and others
3. Make constants instead of variables
4. Remove unused imports
5. Rename classes to simpler names 

```
    public static int startWorkingHour = 10;
    public static int endWorkingHour = 18;
    public static final int START_WORKING_HOUR = 10;
```

**Comment by vmlysenkov** [comment]
fixed
